name: New pull request

on:
  pull_request:
    branches: [develop]

env:
  PR_RELEASE_PATTERN: 'm2tgq-pr-'
  CHANNEL_ID: 'C01CTS1PLQP'

jobs:
  check-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Send slack PR notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_SECRET }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"${{ env.CHANNEL_ID }}\", \"blocks\":[{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*There is a new Pull Request pending for review!*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"• Submitter:\n ${{ github.event.pull_request.user.login }}\n\n • Pull request title: \n ${{ github.event.pull_request.title }} \n\n • Pull Request link: \n <${{ github.event.pull_request.html_url }}|View Pull Request>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"> Quick heads-up! :male-scientist: \n If the build succeeds, we will create a testable url for the PR.\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Have a good day! :wave:\"}},{\"type\":\"divider\"}]}'
      - name: Test the pull request
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build --if-present
          npm run test --if-present
      - name: Notify Slack Success
        if: ${{ success() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_SECRET }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"${{ env.CHANNEL_ID }}\", \"blocks\":[{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Yaay! The build for the PR: _${{ github.event.pull_request.title }}_ has succeeded*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"> Quick heads-up! :construction_worker: \n We are building a testable URL. \n It will soon be available at the following link: <https://${{ env.PR_RELEASE_PATTERN }}${{ github.event.pull_request.number }}.herokuapp.com|View Proof of concept>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Have a good day! :wave:\"}},{\"type\":\"divider\"}]}'
      - name: Notify Slack Failure
        if: ${{ failure() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_SECRET }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"${{ env.CHANNEL_ID }}\", \"blocks\":[{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Oh no! Something went wrong with the pull request! :skull_and_crossbones:*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"> Quick heads-up! :boom: :construction_worker: \n We are no longer building the test branch.\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"You may check the pull request at the following link: \n <${{ github.event.pull_request.html_url }}|View Pull Request>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Have a good day! :wave:\"}},{\"type\":\"divider\"}]}'