name: New pull request

on:
  pull_request:
    branches: [develop]

env:
  PULL_REQUEST_SLACK: '{\"blocks\":[{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*There is a new Pull Request pending for review!*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"• Submitter: \\n ${{ github.event.pull_request.user.login }} \\n • Pull request title: \\n ${{ github.event.pull_request.title }}\\\"}} \\n • Pull Request link: \\n <${{ github.event.pull_request.html_url }}|View Pull Request>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"> Quick heads-up! :male-scientist: \\n If the build succeeds, we will create a testable url for the PR.\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Have a good day! :wave:\"}},{\"type\":\"divider\"}]}'
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_SECRET }}
  ON_ERROR_SLACK: '{\"blocks\":[{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Oh no! Something went wrong with the pull request! :skull_and_crossbones:*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"> Quick heads-up! :boom: :construction_worker: \\n We are no longer building the test branch.\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"You may check the pull request at the following link: \\n <${{ github.event.pull_request.html_url }}|View Pull Request>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Have a good day! :wave:\"}},{\"type\":\"divider\"}]}'
  ON_SUCCESS_SLACK: '"{\"blocks\":[{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Yaay! The build for the PR: ${{ github.event.pull_request.title }} has succeeded*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"> Quick heads-up! :construction_worker: \\n We are building a testable URL. \\n It will soon be available at the following link: <https://${{ PR_RELEASE_PATTERN }}${{ github.event.pull_request.number }}.herokuapp.com|View Proof of concept>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Have a good day! :wave:\"}},{\"type\":\"divider\"}]}"'
  PR_RELEASE_PATTERN: 'm2tgql-pr-'

jobs:
  runs-on: unbuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Send slack notification
      uses: abinoda/slack-action@master
      with:
        args: ${{ env.PULL_REQUEST_SLACK }}

    - name: Test the pull request
      run: |
        if [ -e yarn.lock ]; then
        yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
        npm ci
        else
        npm i
        fi
        if
        npm run build --if-present
        npm run test --if-present
    
    - name: Notify Slack Success
        if: ${{ success() }}
        uses: abinoda/slack-action@master
        with:
          args: ${{ env.ON_SUCCESS_SLACK }}

    - name: Notify Slack Failure
      if: ${{ failure() }}
      uses: abinoda/slack-action@master
      with:
        args: ${{ env.ON_ERROR_SLACK }}